services:
  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - reflex_shorturl
    ports:
      - '6379:6379'
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - reflex_shorturl
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - reflex_shorturl
    ports:
     - 8000:8000
    depends_on:
     - redis
     - database
  frontend:
    build:
      dockerfile: web.Dockerfile
    container_name: frontend
    networks:
      - reflex_shorturl
    ports:
      - 3000:80
    depends_on:
      - backend

networks:
  reflex_shorturl:
    driver: bridge